src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $title;

    #[ORM\Column(type: 'text')]
    private $content;

    #[ORM\ManyToOne(targetEntity: Category::class, inversedBy: 'articles')]
    #[ORM\JoinColumn(nullable: false)]
    private $Category;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $publicationTime = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $author = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $icon = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->Category;
    }

    public function setCategory(?Category $Category): self
    {
        $this->Category = $Category;

        return $this;
    }

    public function getPublicationTime(): ?\DateTimeInterface
    {
        return $this->publicationTime;
    }

    public function setPublicationTime(?\DateTimeInterface $publicationTime): static
    {
        $this->publicationTime = $publicationTime;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(User $author): static
    {
        $this->author = $author;

        return $this;
    }

    public function getIcon(): ?string
    {
        return $this->icon;
    }

    public function setIcon(?string $icon): static
    {
        $this->icon = $icon;

        return $this;
    }
}

src/Controller/BlogController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class BlogController extends AbstractController
{
    private EntityManagerInterface $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    /**
     * Blog home page : render 5 last published articles
     *
     * @return Response
     */
    #[Route('/', name: 'blog')]
    public function index(): Response
    {
        //
        // Get 5 last published articles
        $lastArticles = $this->entityManager->getRepository(Article::class)->createQueryBuilder('a')
            ->orderBy('a.publicationTime', 'ASC')
            ->where('a.publicationTime <= CURRENT_DATE()')
            ->setMaxResults(5)->getQuery()->getResult();

        //
        // Render blog home page
        return $this->render('blog/index.html.twig', [
            'uploadDir' => $this->getParameter('upload_directory'),
            'lastArticles' => $lastArticles
        ]);
    }
}

templates/blog/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    {# Head #}
    <section class="section banner">
        <div class="container">
            <div class="row">
                <div class="col-lg-10">
                    <h2 class="cd-headline clip is-full-width mb-4 ">
                        Bienvenue... <br>
                        <span class="cd-words-wrapper text-color">
                        <b class="is-visible">Sur le blog.</b>
                        <b>Projet porté par Abigail Germon &<br> Aymeric Leger Achard.</b>
                        <b>Profitez !</b>
                    </span>
                    </h2>
                    <p>Pour tester la partie back-office, utilisez les identifiants enregistrés dans le fichier /ReadMe.md</p>
                </div>
            </div>
        </div>
    </section>

    {# Last articles #}
    <section class="section">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <h2 class="mb-2 ">Les derniers articles publiés</h2>
                </div>
            </div>
            <div class="row">
                {% if lastArticles|length == 0 %}
                    {# No article found #}
                    <div class="alert alert-warning">
                        <p>Oh non ! Il n'y a pas d'article pour le moment... Mais ne vous inquiétiez pas, ça arrive bientôt !</p>
                    </div>
                {% else %}
                    <div class="row shuffle-wrapper portfolio-gallery">
                        {# Show last articles #}
                        {% for article in lastArticles %}

                            <div class="col-lg-4 col-6 mb-4 shuffle-item"  data-groups="[&quot;design&quot;,&quot;illustration&quot;]">
                                <div class="position-relative inner-box">
                                    <div class="image position-relative ">
                                        <div class="w-100" style="height: 20rem">
                                            {% if article.icon is not null  %}
                                                <img src="{{ asset('uploads/' ~ article.icon) }}" alt="portfolio-image" class="img-fluid w-100 d-block" style="height: 20rem">
                                            {% else %}
                                                <img src="{{ asset('assets/images/dftArticle.jpeg') }}" alt="portfolio-image" class="img-fluid w-100 h-100 d-block" style="height: 20rem">
                                            {% endif %}
                                        </div>
                                        <div class="overlay-box">
                                            <div class="overlay-inner">
                                                <a class="overlay-content" href="{{ url('article_show', {'id':article.id}) }}">
                                                    <h5 class="mb-0">{{ article.title }}</h5>
                                                    <p>{{ article.category.name }}</p>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        {% endfor %}
                    </div>
                {% endif %}
            </div>
        </div>
    </section>

{% endblock %}